spring.application.name=aqua-link


# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/aqualink-db
spring.datasource.username=postgres
spring.datasource.password=password